services:
  # Production service
  - type: web
    name: yokoai
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd /opt/render/project/src && gunicorn config.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "false"
      - key: CORS_ALLOW_CREDENTIALS
        value: "true"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://yoko.vdmnexus.com,https://www.yoko.vdmnexus.com"
      - key: CORS_ORIGIN_WHITELIST
        value: "https://yoko.vdmnexus.com,https://www.yoko.vdmnexus.com"
      - key: DEBUG
        value: "false"
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src

  # Staging service
  - type: web
    name: yokoai-staging
    env: python
    region: frankfurt
    plan: free
    branch: develop
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: cd /opt/render/project/src && gunicorn config.wsgi:application --bind 0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "false"
      - key: CORS_ALLOW_CREDENTIALS
        value: "true"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://yokoai-staging.vercel.app,https://*.vercel.app"
      - key: CORS_ORIGIN_WHITELIST
        value: "https://yokoai-staging.vercel.app"
      - key: DEBUG
        value: "true"
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src 