services:
  - type: web
    name: yoko-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql://postgres.zcxterglgimuhwxdveed:S9pKaETUozj5cHGX@aws-0-us-east-1.pooler.supabase.com:6543/postgres
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /admin/login/
    regions:
      - ohio  # US East
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 60
    buildFilter:
      paths:
        - requirements.txt
        - config/**
        - api/**
        - agent/** 